version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wealth_app_db
      POSTGRES_USER: wealth_user
      POSTGRES_PASSWORD: wealth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data


  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - gpt-oss-agent
    environment:
      - GPT_AGENT_URL=http://gpt-oss-agent:5000/generate

  gpt-oss-agent:
    build:
      context: ./gpt_oss_agent
    env_file:
      - ./gpt_oss_agent/.env
    ports:
      - "5000:5000"

volumes:
  postgres_data:
  redis_data:
