name: Deprecated (Do not use)
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This workflow is deprecated."
          echo "Use backend-ci.yml and docker-build.yml instead."
