name: Trivy Container Scan

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          load: true
          tags: local/gpt-oss-agent-backend:pr-${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy scan (fs + image)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: local/gpt-oss-agent-backend:pr-${{ github.run_id }}
          format: sarif
          output: trivy-results.sarif
          vuln-type: 'os,library'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
